### ISSUE TITLE
Getting the list of programs

### ISSUE THREAD

**Issue by thipages** [mat-tso/arte.tv#1]
Hi,
First thanks for the code. Great!
Is it possible to get the list of arte programmes?

**Comment by mat-tso** [comment]
Hi thipages,
I am not sure what you mean by "get the list of Arte programmes". You can browse the Arte videos at www.arte.tv. Or do you mean generate programmatically a table with all Arte programs ?

**Comment by thipages** [comment]
Hi,
sorry, it was not clear.
Since we need an id to retrieve the json file, I was asking you if there is a list of these ids somewhere?
Probably not all ids, but the ones of the week.

**Comment by thipages** [comment]
I get it (working), See : [https://github.com/RSS-Bridge/rss-bridge/issues/524#issuecomment-304857517](https://github.com/RSS-Bridge/rss-bridge/issues/524#issuecomment-304857517).
But I dont know where the autorizations come from...

**Comment by mat-tso** [comment]
I have no idea. I could hardly find any documentation on the API. I only created this as a fun weekend project.
I can not help you, sorry.

**Comment by thipages** [comment]
Hi
Nice weekend project!  Thanks
